# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ldpc_decoder_xdc.xdc

# IP: ip/c_addsub_0/c_addsub_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_0 || ORIG_REF_NAME==c_addsub_0} -quiet] -quiet

# IP: ip/RAM_288_1/RAM_288_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_288_1 || ORIG_REF_NAME==RAM_288_1} -quiet] -quiet
