# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.cache/wt [current_project]
set_property parent.project_path E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/ROM_h.coe
read_verilog -library xil_defaultlib {
  E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/new/CNU_unit.v
  E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/new/abs.v
  E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/new/compute.v
  E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/new/control_decode.v
  E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/new/data_load.v
  E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/new/data_out.v
  E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/new/find_min.v
  E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/new/judge.v
  E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/new/judge_unit1.v
  E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/new/judge_unit2.v
  E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/new/load_app.v
  E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/new/multiplier.v
  E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/new/nms_control.v
  E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/new/nms_decode.v
  E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/new/prod.v
  E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/new/pu.v
  E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/new/ram_app.v
  E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/new/startup.v
  E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/new/update_app.v
  E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/new/update_unit.v
  E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/new/top_module.v
}
read_ip -quiet e:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/ip/c_addsub_0/c_addsub_0.xci
set_property used_in_implementation false [get_files -all e:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/ip/c_addsub_0/c_addsub_0_ooc.xdc]

read_ip -quiet E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/ip/RAM_288_1/RAM_288_1.xci
set_property used_in_implementation false [get_files -all e:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/ip/RAM_288_1/RAM_288_1_ooc.xdc]

read_ip -quiet E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/ip/ram_r_50/ram_r_50.xci
set_property used_in_implementation false [get_files -all e:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/ip/ram_r_50/ram_r_50_ooc.xdc]

read_ip -quiet E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/ip/ram_app_16/ram_app_16.xci
set_property used_in_implementation false [get_files -all e:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/ip/ram_app_16/ram_app_16_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/constrs_1/new/ldpc_decoder_xdc.xdc
set_property used_in_implementation false [get_files E:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/constrs_1/new/ldpc_decoder_xdc.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_module -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_module.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
