# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/ip/ram_r_50/ram_r_50.xci
# IP: The module: 'ram_r_50' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/ip/ram_r_50/ram_r_50_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_r_50'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/ip/ram_r_50/ram_r_50.xci
# IP: The module: 'ram_r_50' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_Source/XILINX/LDPC-F/Decoder_2/ldpc_decoder.srcs/sources_1/ip/ram_r_50/ram_r_50_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_r_50'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
